apiVersion: v2
name: ill-cloud
description: A Helm chart for deploying an Elysia.js API to Kubernetes
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: ingress-nginx
  version: "4.12.0"
  repository: "https://kubernetes.github.io/ingress-nginx"
- name: cert-manager
  version: "1.17.1"
  repository: "https://charts.jetstack.io"
