apiVersion: v2
name: nextjs-app
description: A Helm chart for deploying an Elysia.js API with ArgoCD, Nginx Ingress, and Cert Manager
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: nginx-ingress
    repository: "https://kubernetes.github.io/ingress-nginx"
  - name: cert-manager
    repository: "https://charts.jetstack.io"
