replicaCount: 2

deployment:
  namespace: ill-cloud

image:
  repository: illustriousonline/ill-cloud
  tag: 1.0.10
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: api.illustrious.cloud
  path: /
  pathType: Prefix
  tlsSecretName: api-tls

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
