name: "Illustrious Cloud Release"
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
jobs:
  cloud-release:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    env:
      IS_NEW_VERSION: false
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      SPACE_URL: https://${{ secrets.SPACE_NAME }}.${{ secrets.SPACE_REGION }}.digitaloceanspaces.com
    steps:
      ### Install server dependencies
      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5
        with:
          bun-version: latest
      - name: Install doctl
        uses: digitalocean/action-doctl@135ac0aa0eed4437d547c6f12c364d3006b42824
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Install spaces-cli
        run: bun install -g spaces-cli
      ### Clone repository & install application dependencies
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Ensure we are on the main branch
        run: |
          git checkout main
          git pull origin main --tags
      - name: Download test dependency files
        run: |
          spaces-cli down $SPACE_URL/cloud/ci.env -o ./.env -k ${{ secrets.SPACE_SECRET }} -i ${{ secrets.SPACE_KEY }}
          spaces-cli down $SPACE_URL/cloud/certificate-pub.crt -o ./cert.crt -k ${{ secrets.SPACE_SECRET }} -i ${{ secrets.SPACE_KEY }}
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      ### Push database migrations
      - name: Add actions IP to trusted source for database
        run: |
          IP=$(curl -s ifconfig.me)
          doctl databases firewalls append ${{ secrets.DB_UUID }} --rule ip_addr:$IP
      - name: Push database migrations
        run: |
          export NODE_TLS_REJECT_UNAUTHORIZED=0
          bunx drizzle-kit migrate
          export NODE_TLS_REJECT_UNAUTHORIZED=1
      - name: Remove actions IP to trusted source for database
        run: |
          IP=$(curl -s ifconfig.me)
          JSON=$(doctl databases firewalls list ${{ secrets.DB_UUID }} --output json)
          ID=$(echo $JSON | jq -r '.[] | select(.value == '\"$IP\"').uuid')
          doctl databases firewalls remove ${{ secrets.DB_UUID }} --uuid $ID
      ### Set up production environment variables
      - name: Download production environment variables
        run: |
          rm -rf .env cert.crt
          spaces-cli down $SPACE_URL/cloud/production.env -o .env -k ${{ secrets.SPACE_SECRET }} -i ${{ secrets.SPACE_KEY }}
          spaces-cli down $SPACE_URL/cloud/certificate-vpc.crt -o ./cert.crt -k ${{ secrets.SPACE_SECRET }} -i ${{ secrets.SPACE_KEY }}
      ### Build new docker image with new version
      - name: Build the application
        run: bun run build
      ### Build new docker image as latest version
      - name: Build and push latest Docker image
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.REGISTRY_URL }}:latest .
          docker push ${{ secrets.REGISTRY_URL }}:latest
      - name: Compare versions
        id: compare
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          NEXT_VERSION=$(bunx semantic-release --dry-run | grep 'The next release version is' | awk '{print $NF}')
          if [ "$CURRENT_VERSION" = "$NEXT_VERSION" ]; then
            echo "IS_NEW_VERSION=true" >> $GITHUB_ENV
          else
            echo "IS_NEW_VERSION=false" >> $GITHUB_ENV
          fi
      - name: Get next version
        run: |
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV
      ### Push new versioned Docker image to registry
      - name: Push versioned Docker image to registry, if updated
        if: env.IS_NEW_VERSION == 'true'
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.REGISTRY_URL }}:${{ env.NEXT_VERSION }} .
          docker push ${{ secrets.REGISTRY_URL }}:${{ env.NEXT_VERSION }}
          sed -i "s/tag: .*/tag: ${{ env.NEXT_VERSION }}/" k8s/values.yaml
          sed -i "s/version: .*/version: ${{ env.NEXT_VERSION }}/" k8s/Chart.yaml
          sed -i 's/appVersion: .*/appVersion: "'${{ env.NEXT_VERSION }}'"/' k8s/Chart.yaml
          jq --arg newVersion "${{ env.NEXT_VERSION }}" '.version = $newVersion' package.json > tmp.json && mv tmp.json package.json
      ### Push argo-cd application updates
      - name: Push argo-cd application updates, if updated
        if: env.IS_NEW_VERSION == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git add k8s
          git commit -m "chore: Prepare deployment (${{ env.NEXT_VERSION }}) [skip ci]"
          git push origin main
      ### Execute final versioning updates via semantic-release
      - name: Execute semantic-release
        run: bunx semantic-release
